### ISSUE TITLE
기타 TODO list

### ISSUE THREAD

**Issue by cyberjam** [LifeIsAlone/public-home#54]
순서 : 중요도 순

* 반드시 필요함
- [ ] 데이터 get 완전 자동화
- [ ] seo
- [ ] 반응형 (또는 모바일환경에서 접속 안되게라도)
- [ ] 성별, 지역 등 필터 

* 있으면 좋음
- [ ] 엑셀 필터링시 바로 deploy?
- [ ] 네이버 지도 해당 위치 바로가기 or 로드뷰
- [ ] 가격 기준 drawer에 정렬

* 부가기능. 없어도 괜찮음.
- [ ] 거리 및 반경
- [ ] 주소 부분 복사 아이콘
- [ ] 찜기능
- [x] 검색기능

**Comment by ParkAward** [comment]
### 검색기능
#60
